project_id = "aclcnbhhvxhtmwrqzave"

[functions.oauth-callback]
verify_jwt = false

[functions.oauth-start]
verify_jwt = false

[functions.test-webhook]
verify_jwt = false

[functions.test-netsuite]
verify_jwt = false

[functions.approve-and-push]
verify_jwt = true
